### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by brockboland** [enova/career_ladders#1]
> [Enova](http://www.enova.com) has decided to open source it's career ladders. You can find background on why we created new ladders [here](https://www.enova.com/blog/open-sourcing-engineering-ladders/) and why we open sourced them [here]().

That last `here` is missing a URL and GitHub does weird things when rendering the Markdown (like linking to https://github.com/enova/career_ladders/blob/master). Not sure where that was supposed to go.

**Comment by gcaprio** [comment]
Thanks @brockboland ! merged.
