### ISSUE TITLE
Why Ugly Markdown

### ISSUE THREAD

**Issue by anderson-dan-w** [enova/career_ladders#8]
Haven't had a chance to play around with it, and it would look less clean in the raw text file, but (this SO answer)[http://stackoverflow.com/a/19976953/2272638] seems to suggest you can do multi-line tables in GFM with a little care. Dunno if it's worth it, but figured I'd at least mention.

**Comment by gcaprio** [comment]
Thanks @anderson-dan-w We're working on a revamp now.
